// AUTOGENERATED by exporter.py from Reflect.java
package pyjvm.modules.reflect;

import pyjvm.*;

public final class ReflectClass extends Type {
	private ReflectClass() {}

	public static final StringDict dict;
	public static final ReflectClass instance = new ReflectClass();
	public static final Obj constructor = null;
	
	static {
		if("Reflect".equals("NativeObj") || "Reflect".equals("UserObj"))
			dict = new StringDict();
		else
			dict = NativeObjClass.dict.copy();
		
		dict.put("get_class", new Obj() {
			public Obj call(Obj[] args) {
				if(args.length != 1) {
					throw new ScriptError(ScriptError.TypeError, "Bad number of arguments");
				}
				return Reflect.get_class(args[0]);
			}
		});
	}
	public final StringDict getDict() {
		return dict;
	}
	public final Obj getEntry(int name) {
		return dict.get(name);
	}
	public final Obj call(Obj[] args) {
		if(constructor == null)
			throw new ScriptError(ScriptError.TypeError, "Object uninitializable");
		return constructor.call(args);
	}
}
