// AUTOGENERATED by exporter.py from BaseString.java
package pyjvm;

public final class BaseStringClass extends Type {
	private BaseStringClass() {}

	public static final StringDict dict;
	public static final BaseStringClass instance = new BaseStringClass();
	public static final Obj constructor = null;

	static {
		if("BaseString".equals("NativeObj") || "BaseString".equals("UserObj"))
			dict = new StringDict();
		else
			dict = NativeObjClass.dict.copy();

	}
	public final StringDict getDict() {
		return dict;
	}
	public final Obj getEntry(int name) {
		return dict.get(name);
	}
	public final Obj call(Obj[] args) {
		if(constructor == null)
			throw new ScriptError(ScriptError.TypeError, "Object uninitializable");
		return constructor.call(args);
	}
}
