// AUTOGENERATED by exporter.py from Dict.java
package pyjvm;

import pyjvm.*;

public final class DictClass extends Type {
	private DictClass() {}

	public static final StringDict dict;
	public static final DictClass instance = new DictClass();
	public static final Obj constructor = null;

	static {
		if("Dict".equals("NativeObj") || "Dict".equals("UserObj"))
			dict = new StringDict();
		else
			dict = NativeObjClass.dict.copy();
	}
	public final StringDict getDict() {
		return dict;
	}
	public final Obj getEntry(int name) {
		return dict.get(name);
	}
	public final Obj call(Obj[] args) {
		if(constructor == null)
			throw new ScriptError(ScriptError.TypeError, "Object uninitializable");
		return constructor.call(args);
	}
}
