// AUTOGENERATED by exporter.py from Instr.java
package pyjvm;

import pyjvm.*;

public final class InstrClass extends Type {
	private InstrClass() {}

	public static final StringDict dict;
	public static final InstrClass instance = new InstrClass();
	public static final Obj constructor = null;

	static {
		if("Instr".equals("NativeObj") || "Instr".equals("UserObj"))
			dict = new StringDict();
		else
			dict = NativeObjClass.dict.copy();

		dict.put("run", new Method() {
			public Obj callMethod(Obj self, Obj[] args) {
				if(args.length != 1) {
					throw new ScriptError(ScriptError.TypeError, "Bad number of arguments (expected 1, got " + args.length + ")");
				}
				((Instr)self).run(args[0]); return None;
			}
		});
	}
	public final StringDict getDict() {
		return dict;
	}
	public final Obj getEntry(int name) {
		return dict.get(name);
	}
	public final Obj call(Obj[] args) {
		if(constructor == null)
			throw new ScriptError(ScriptError.TypeError, "Object uninitializable");
		return constructor.call(args);
	}
}
