// AUTOGENERATED by exporter.py from SFloat.java
package pyjvm;

import pyjvm.*;

public final class SFloatClass extends Type {
	private SFloatClass() {}

	public static final StringDict dict;
	public static final SFloatClass instance = new SFloatClass();
	public static final Obj constructor = null;

	static {
		if("SFloat".equals("NativeObj") || "SFloat".equals("UserObj"))
			dict = new StringDict();
		else
			dict = NativeObjClass.dict.copy();

	}
	public final StringDict getDict() {
		return dict;
	}
	public final Obj getEntry(int name) {
		return dict.get(name);
	}
	public final Obj call(Obj[] args) {
		if(constructor == null)
			throw new ScriptError(ScriptError.TypeError, "Object uninitializable");
		return constructor.call(args);
	}
}
