// AUTOGENERATED by exporter.py from SInt.java
package pyjvm;

import pyjvm.*;

public final class SIntClass extends Type {
	private SIntClass() {}

	public static final StringDict dict;
	public static final SIntClass instance = new SIntClass();
	public static final Obj constructor = null;

	static {
		if("SInt".equals("NativeObj") || "SInt".equals("UserObj"))
			dict = new StringDict();
		else
			dict = NativeObjClass.dict.copy();

	}
	public final StringDict getDict() {
		return dict;
	}
	public final Obj getEntry(int name) {
		return dict.get(name);
	}
	public final Obj call(Obj[] args) {
		if(constructor == null)
			throw new ScriptError(ScriptError.TypeError, "Object uninitializable");
		return constructor.call(args);
	}
}
