// AUTOGENERATED by exporter.py from SString.java
package pyjvm;

import pyjvm.*;

public final class SStringClass extends Type {
	private SStringClass() {}

	public static final StringDict dict;
	public static final SStringClass instance = new SStringClass();
	public static final Obj constructor;
	
	static {
		if("SString".equals("NativeObj") || "SString".equals("UserObj"))
			dict = new StringDict();
		else
			dict = BaseStringClass.dict.copy();
		
		dict.put("repr_bytes", new Method() {
			public Obj callMethod(Obj self, Obj[] args) {
				if(args.length != 0) {
					throw new ScriptError(ScriptError.TypeError, "Bad number of arguments (expected 0, got " + args.length + ")");
				}
				return ((SString)self).repr_bytes();
			}
		});
		dict.put("join", new Method() {
			public Obj callMethod(Obj self, Obj[] args) {
				if(args.length != 1) {
					throw new ScriptError(ScriptError.TypeError, "Bad number of arguments (expected 1, got " + args.length + ")");
				}
				return ((SString)self).join(args[0]);
			}
		});
		constructor = new Obj() {
			public Obj call(Obj[] args)  {
				if(args.length != 1) {
					throw new ScriptError(ScriptError.TypeError, "Bad number of arguments (expected 1, got " + args.length + ")");
				}
				return SString.construct(args[0]);
			}
		};
		
		dict.put("strip", new Method() {
			public Obj callMethod(Obj self, Obj[] args) {
				if(args.length != 0) {
					throw new ScriptError(ScriptError.TypeError, "Bad number of arguments (expected 0, got " + args.length + ")");
				}
				return ((SString)self).strip();
			}
		});
		dict.put("lower", new Method() {
			public Obj callMethod(Obj self, Obj[] args) {
				if(args.length != 0) {
					throw new ScriptError(ScriptError.TypeError, "Bad number of arguments (expected 0, got " + args.length + ")");
				}
				return ((SString)self).lower();
			}
		});
		dict.put("upper", new Method() {
			public Obj callMethod(Obj self, Obj[] args) {
				if(args.length != 0) {
					throw new ScriptError(ScriptError.TypeError, "Bad number of arguments (expected 0, got " + args.length + ")");
				}
				return ((SString)self).upper();
			}
		});
		dict.put("contains", new Method() {
			public Obj callMethod(Obj self, Obj[] args) {
				if(args.length != 1) {
					throw new ScriptError(ScriptError.TypeError, "Bad number of arguments (expected 1, got " + args.length + ")");
				}
				return ((SString)self).contains(args[0])? SBool.True: SBool.False;
			}
		});
		dict.put("find", new Method() {
			public Obj callMethod(Obj self, Obj[] args) {
				// direct
				return SInt.get(((SString)self).find(args));
			}
		});
	}
	public final StringDict getDict() {
		return dict;
	}
	public final Obj getEntry(int name) {
		return dict.get(name);
	}
	public final Obj call(Obj[] args) {
		if(constructor == null)
			throw new ScriptError(ScriptError.TypeError, "Object uninitializable");
		return constructor.call(args);
	}
}
