// AUTOGENERATED by exporter.py from Tuple.java
package pyjvm;

import pyjvm.*;

public final class TupleClass extends Type {
	private TupleClass() {}

	public static final StringDict dict;
	public static final TupleClass instance = new TupleClass();
	public static final Obj constructor = null;
	
	static {
		if("Tuple".equals("NativeObj") || "Tuple".equals("UserObj"))
			dict = new StringDict();
		else
			dict = NativeObjClass.dict.copy();
		
	}
	public final StringDict getDict() {
		return dict;
	}
	public final Obj getEntry(int name) {
		return dict.get(name);
	}
	public final Obj call(Obj[] args) {
		if(constructor == null)
			throw new ScriptError(ScriptError.TypeError, "Object uninitializable");
		return constructor.call(args);
	}
}
