// AUTOGENERATED by exporter.py from UserObj.java
package pyjvm;

public final class UserObjClass extends Type {
	private UserObjClass() {}

	public static final StringDict dict;
	public static final UserObjClass instance = new UserObjClass();
	public static final Obj constructor = null;
	
	static {
		if("UserObj".equals("NativeObj") || "UserObj".equals("UserObj"))
			dict = new StringDict();
		else
			dict = NativeObjClass.dict.copy();
		
		dict.put("__init__", new Method() {
			public Obj callMethod(Obj self, Obj[] args) {
				// direct
				return ((UserObj)self).__init__(args);
			}
		});
	}
	public final StringDict getDict() {
		return dict;
	}
	public final Obj getEntry(int name) {
		return dict.get(name);
	}
	public final Obj call(Obj[] args) {
		if(constructor == null)
			throw new ScriptError(ScriptError.TypeError, "Object uninitializable");
		return constructor.call(args);
	}
}
