// AUTOGENERATED by exporter.py from Sys.java
package pyjvm.modules;

import pyjvm.*;

public final class SysClass extends Type {
	private SysClass() {}

	public static final StringDict dict;
	public static final SysClass instance = new SysClass();
	public static final Obj constructor = null;
	
	static {
		if("Sys".equals("NativeObj") || "Sys".equals("UserObj"))
			dict = new StringDict();
		else
			dict = NativeObjClass.dict.copy();
		
		dict.put("unserialize", new Obj() {
			public Obj call(Obj[] args) {
				if(args.length != 1) {
					throw new ScriptError(ScriptError.TypeError, "Bad number of arguments (expected 1, got " + args.length + ")");
				}
				return Sys.unserialize(args[0]);
			}
		});
		dict.put("catch_errors", new Obj() {
			public Obj call(Obj[] args) {
				if(args.length != 1) {
					throw new ScriptError(ScriptError.TypeError, "Bad number of arguments (expected 1, got " + args.length + ")");
				}
				return Sys.catch_errors(args[0]);
			}
		});
	}
	public final StringDict getDict() {
		return dict;
	}
	public final Obj getEntry(int name) {
		return dict.get(name);
	}
	public final Obj call(Obj[] args) {
		if(constructor == null)
			throw new ScriptError(ScriptError.TypeError, "Object uninitializable");
		return constructor.call(args);
	}
}
